name: Download Redrix Firmware

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch ROM via Curl with Full Mirror
        run: |
          mkdir -p output
          # Telechargement direct du miroir avec suivi des redirections HTTP/2
          curl -L -k -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:125.0) Gecko/20100101 Firefox/125.0" \
               -e "https://mrchromebox.tech/" \
               -o output/redrix_coreboot.rom \
               "https://mrchromebox.tech/files/firmware/full_rom/coreboot_tianocore-redrix-mrchromebox_20240519.rom"
          
          # Verification de la taille dans la console
          ls -lh output/

      - name: Upload ROM Artifact
        uses: actions/upload-artifact@v4
        with:
          name: redrix-coreboot-rom
          path: output/redrix_coreboot.rom
